### PR TITLE
Price search on the stores Steam, Nuuvem, Epic Games and Playstation Store.

### PR DESCRIPTION
**Pull request by RicardoKromerCavati**
Project organization in folders, models, enums and interfaces creation, response classes, unification of price search, http requests, gettting a list of prices from all stores to show on the presentation.

### CODE REVIEW

**Review by rodrigoTajima — APPROVED** [review]

**Review by Bruno-Cunha-Souza — APPROVED** [review]
Muito bom

**Review by rodrigoTajima — APPROVED** [review]
LGTM

**Review by Johnman67112 — APPROVED** [review]
LGTM

**Review by Brulogg — APPROVED** [review]
LGTM

**Pull request merged**
